"""edit

Revision ID: 065465813049
Revises: cc070b9b6781
Create Date: 2021-05-19 14:45:02.889489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065465813049'
down_revision = 'cc070b9b6781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('created_date', sa.Date(), nullable=True))
    op.drop_column('advertisement', 'created_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement', sa.Column('created_data', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('advertisement', 'created_date')
    # ### end Alembic commands ###
